name: Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: vladimirkutuev/cmocka:latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and test source code
        run: |
         mkdir -p cmake_build && \
         cd ./cmake_build && \
         cmake .. && \
         make && \
         ctest --verbose

